### ISSUE TITLE
java.lang.IllegalAccessError: tried to access method org.apache.avro.specific.SpecificData.<init>()V from class com.alibaba.dts.formats.avro.Record

### ISSUE THREAD

**Issue by peak-xu** [LioRoger/subscribe_example#16]
java.lang.IllegalAccessError: tried to access method org.apache.avro.specific.SpecificData.<init>()V from class com.alibaba.dts.formats.avro.Record
	at com.alibaba.dts.formats.avro.Record.<clinit>(Record.java:20)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.table.descriptors.DescriptorProperties.lambda$getOptionalClass$2(DescriptorProperties.java:283)
	at java.util.Optional.map(Optional.java:215)
	at org.apache.flink.table.descriptors.DescriptorProperties.getOptionalClass(DescriptorProperties.java:280)
	at org.apache.flink.table.descriptors.DescriptorProperties.getClass(DescriptorProperties.java:300)
	at org.apache.flink.formats.avro.AvroRowFormatFactory.createDeserializationSchema(AvroRowFormatFactory.java:62)
	at org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactoryBase.getDeserializationSchema(KafkaTableSourceSinkFactoryBase.java:263)
	at org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactoryBase.createStreamTableSource(KafkaTableSourceSinkFactoryBase.java:144)
	at org.apache.flink.table.factories.TableFactoryUtil$.findAndCreateTableSource(TableFactoryUtil.scala:50)
	at org.apache.flink.table.descriptors.ConnectTableDescriptor.registerTableSource(ConnectTableDescriptor.scala:46)
	at com.flink.sql.ParcelInfo.main(ParcelInfo.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.ja

使用flink avro反序列化dts数据 报的错,大佬又遇到的吗

**Comment by Jardinsjian** [comment]
你好，问一下，你们是 flink  消费的数据格式是avro的，也是dts 同步rds数据到kafka的吗？

**Comment by peak-xu** [comment]
直接消费dts订阅通道的数据

**Comment by Jardinsjian** [comment]
不是 dts 把数据同步到kafka，然后再用flink消费啊？
如果直接消费dts订阅通道的数据，有什么文档吗，参考下。谢啦！

**Comment by peak-xu** [comment]
消费dts订阅通道的数据，就是和kafka客户端消费一模一样，API也是一样的
https://help.aliyun.com/document_detail/121239.html?spm=a2c4g.11186623.6.760.2cd21fednH5RR5

**Comment by Jardinsjian** [comment]
是的，我们也是这个方式，只不过是，我们多了一个流程，就是用dts把数据同步到kafka，然后 阿里云原生flink 计算平台上运行flink任务 消费解析 avro数据。但是目前遇到点问题，不知道能不能请大佬帮忙：
AvroDeserializationSchema<Record> UserSchema = AvroDeserializationSchema.forSpecific(Record.class);
        FlinkKafkaConsumer consumer = new FlinkKafkaConsumer(topicName, UserSchema, properties);
这个是我flink中使用的解析方式，但是任务运行后，就会一直报 java.lang.OutOfMemoryError: Java heap space  但是看数据量并不大，我把taskmanager调大，也是一样的，不知道你们有没有遇见这个问题。或者可以帮忙提供下你们 flink 消费解析的方式。谢啦！

**Comment by peak-xu** [comment]
没有遇见过这种问题，解析错误的话不会报内存的错误吧

**Comment by Jardinsjian** [comment]
解析应该没有问题，可能是我们使用k8s的问题吧，资源申请的问题，我再调试下。

**Comment by peak-xu** [comment]
我们目前用的emr，在yarn上跑作业

**Comment by Jardinsjian** [comment]
嗯嗯，谢啦。

**Comment by Jardinsjian** [comment]
请教下：
你是用这个方式解析的吗：
AvroDeserializationSchema UserSchema = AvroDeserializationSchema.forSpecific(Record.class);
FlinkKafkaConsumer consumer = new FlinkKafkaConsumer(topicName, UserSchema, properties);

**Comment by peak-xu** [comment]
是的，你可以本地调试一下看看数据有没有解析呢
