### ISSUE TITLE
flink  解析  avro数据报内存溢出

### ISSUE THREAD

**Issue by Jardinsjian** [LioRoger/subscribe_example#19]
我们数据量很少的，就几万条，但是任务启动就报这个错误？？
java.lang.OutOfMemoryError: Java heap space
	at org.apache.avro.util.Utf8.setByteLength(Utf8.java:78) ~[usercode.jar:?]
	at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:261) ~[usercode.jar:?]
	at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:272) ~[usercode.jar:?]
	at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:214) ~[usercode.jar:?]
	at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:412) ~[usercode.jar:?]
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:181) ~[usercode.jar:?]
	at org.apache.avro.specific.SpecificDatumReader.readField(SpecificDatumReader.java:116) ~[usercode.jar:?]
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:222) ~[usercode.jar:?]
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175) ~[usercode.jar:?]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153) ~[usercode.jar:?]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145) ~[usercode.jar:?]
	at org.apache.flink.formats.avro.AvroDeserializationSchema.deserialize(AvroDeserializationSchema.java:135) ~[usercode.jar:?]
	at org.apache.flink.streaming.connectors.kafka.internals.KafkaDeserializationSchemaWrapper.deserialize(KafkaDeserializationSchemaWrapper.java:45) ~[usercode.jar:?]
	at org.apache.flink.streaming.connectors.kafka.internal.KafkaFetcher.runFetchLoop(KafkaFetcher.java:140) ~[usercode.jar:?]
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:715) ~[usercode.jar:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100) ~[flink-dist_2.11-1.10-vvr-1.0.1-SNAPSHOT.jar:1.10-vvr-1.0.1-SNAPSHOT]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63) ~[flink-dist_2.11-1.10-vvr-1.0.1-SNAPSHOT.jar:1.10-vvr-1.0.1-SNAPSHOT]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:196) ~[flink-dist_2.11-1.10-vvr-1.0.1-SNAPSHOT.jar:1.10-vvr-1.0.1-SNAPSHOT]

**Comment by LioRoger** [comment]
你可以查看一下blink里面消费的代码他的decoder是否是复用的，如果是复用的，上游的schema变化回到这个内存错乱，每次都重新初始化decoder就可以了，这个在之前的一个flink的用户中发现过这个问题

**Comment by Tasselmi** [comment]
> 我们数据量很少的，就几万条，但是任务启动就报这个错误？？
> java.lang.OutOfMemoryError: Java heap space
> at org.apache.avro.util.Utf8.setByteLength(Utf8.java:78) ~[usercode.jar:?]
> at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:261) ~[usercode.jar:?]
> at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:272) ~[usercode.jar:?]
> at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:214) ~[usercode.jar:?]
> at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:412) ~[usercode.jar:?]
> at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:181) ~[usercode.jar:?]
> at org.apache.avro.specific.SpecificDatumReader.readField(SpecificDatumReader.java:116) ~[usercode.jar:?]
> at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:222) ~[usercode.jar:?]
> at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175) ~[usercode.jar:?]
> at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153) ~[usercode.jar:?]
> at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145) ~[usercode.jar:?]
> at org.apache.flink.formats.avro.AvroDeserializationSchema.deserialize(AvroDeserializationSchema.java:135) ~[usercode.jar:?]
> at org.apache.flink.streaming.connectors.kafka.internals.KafkaDeserializationSchemaWrapper.deserialize(KafkaDeserializationSchemaWrapper.java:45) ~[usercode.jar:?]
> at org.apache.flink.streaming.connectors.kafka.internal.KafkaFetcher.runFetchLoop(KafkaFetcher.java:140) ~[usercode.jar:?]
> at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:715) ~[usercode.jar:?]
> at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100) ~[flink-dist_2.11-1.10-vvr-1.0.1-SNAPSHOT.jar:1.10-vvr-1.0.1-SNAPSHOT]
> at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63) ~[flink-dist_2.11-1.10-vvr-1.0.1-SNAPSHOT.jar:1.10-vvr-1.0.1-SNAPSHOT]
> at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:196) ~[flink-dist_2.11-1.10-vvr-1.0.1-SNAPSHOT.jar:1.10-vvr-1.0.1-SNAPSHOT]

老哥，怎么用flink解析这个订阅的数据啊，我也正在做这个项目。你有git可以参考的吗，谢谢了
